services:
  postgres:
    image: postgres:14.8
    container_name: cloud_docker_compose
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: cloud
      POSTGRES_DB: cloud
    volumes:
      - postgres_data_cloud:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass 123
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    restart: unless-stopped
    command: server /data --console -address:9001

volumes:
  postgres_data_cloud:
  minio_data: