spring:

  datasource:
    username: cloud
    password: cloud
    url: jdbc:postgresql://localhost:5434/cloud
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  cache:
    type: redis

  session:
    timeout: 1h
    redis:
      flush-mode: on_save
      namespace: spring:session

  data:
    redis:
      host: localhost
      port: 6379
      password: 123