spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    org.springframework.data.redis: DEBUG
    org.springframework.session: DEBUG
    org.springframework.security: DEBUG